const produtos = [
    {
      id:1,
      descricao:"DREHER ",
      minimo:15,
      preco:10.00,
      preco_atacado:8.00,
      quantidade_atacado:12,
      comissao:10,
      cd_barra:"85832",
      data:new Date(),
      escaninho:1,
      tipo:"revenda",
    },
    {
      id:2,
      descricao:"BRAHMA LATAO 473ml",
      minimo:15,
      preco:5.00,
      preco_atacado:4.00,
      quantidade_atacado:12,
      comissao:10,
      cd_barra:"978325",
      data:new Date(),
      escaninho:2,
      tipo:"revenda",
    },
    {
      id:3,
      descricao:"VODKA ORLOFF",
      minimo:15,
      preco:22.00,
      preco_atacado:22.00,
      quantidade_atacado:12,
      comissao:10,
      cd_barra:"790350",
      data:new Date(),
      escaninho:3,
      tipo:"revenda",
    },
    {
      id:4,
      descricao:"COCA-COLA LATA 350ML",
      minimo:15,
      preco:3.50,
      preco_atacado:3.00,
      quantidade_atacado:12,
      comissao:10,
      cd_barra:"85832215",
      data:new Date(),
      escaninho:4,
      tipo:"revenda",
    },
    {
      id:5,
      descricao:"GUARANA LATA 350 ML",
      minimo:15,
      preco:3.50,
      preco_atacado:3.00,
      quantidade_atacado:12,
      comissao:10,
      cd_barra:"85832215",
      data:new Date(),
      escaninho:5,
      tipo:"revenda",
    },
    {
      id:6,
      descricao:"LICOR 43",
      minimo:15,
      preco:120.00,
      preco_atacado:100.00,
      quantidade_atacado:3,
      comissao:10,
      cd_barra:"858322152030",
      data:new Date(),
      escaninho:6,
      tipo:"revenda",
    },
    {
      id:7,
      descricao:"AMARULA 700ML",
      minimo:15,
      preco:140.00,
      preco_atacado:120.00,
      quantidade_atacado:3,
      comissao:10,
      cd_barra:"858322154041",
      data:new Date(),
      escaninho:7,
      tipo:"revenda",
    },
    {
      id:8,
      descricao:"RED LABEL 1LITRO",
      minimo:15,
      preco:92.00,
      preco_atacado:85.00,
      quantidade_atacado:2,
      comissao:10,
      cd_barra:"858329653",
      data:new Date(),
      escaninho:8,
      tipo:"revenda",
    },
    {
      id:9,
      descricao:"CONTINI",
      minimo:15,
      preco:28.00,
      preco_atacado:28.00,
      quantidade_atacado:1,
      comissao:10,
      cd_barra:"858322151030",
      data:new Date(),
      escaninho:9,
      tipo:"revenda",
    },
    {
      id:10,
      descricao:"HEINEKEN LATAO 473ML",
      minimo:15,
      preco:6.00,
      preco_atacado:6.00,
      quantidade_atacado:1,
      comissao:10,
      cd_barra:"858322151040",
      data:new Date(),
      escaninho:10,
      tipo:"revenda",
    },
    
  ]

  


  //console.log(produtos);
  module.exports = produtos;
